subprojects {

    apply plugin: 'java'
    apply plugin: 'org.springframework.boot'

    dependencies {
        // BOM
        implementation platform(project(':bom'))
        compileOnly platform(project(':bom'))
        annotationProcessor platform(project(':bom'))
        testCompileOnly platform(project(':bom'))
        testAnnotationProcessor platform(project(':bom'))
        // Starters
        implementation(project(':starters:common'))
        // Web MVC
        implementation 'org.springframework.boot:spring-boot-starter-webmvc'
        // openapi
        implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui'
        // mapstruct
        implementation 'org.mapstruct:mapstruct'
        annotationProcessor 'org.mapstruct:mapstruct-processor'
        annotationProcessor 'org.projectlombok:lombok-mapstruct-binding'
        // lombok
        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'
        testCompileOnly 'org.projectlombok:lombok'
        testAnnotationProcessor 'org.projectlombok:lombok'
        // tools
        developmentOnly 'org.springframework.boot:spring-boot-devtools'
        developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
        // Eureka
        implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
        // test core
        testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    tasks.named('test') {
        useJUnitPlatform()
    }
}