services:
  postgres:
    image: 'postgres:17.11'
    container_name: 'core'
    environment:
      - 'POSTGRES_DB=${ECOMMERCE_DB}'
      - 'POSTGRES_PASSWORD=${ECOMMERCE_DB_PASSWORD}'
      - 'POSTGRES_USER=${ECOMMERCE_DB_USER}'
    command: postgres -c timezone=UTC
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: 'redis:8.10.1'
    container_name: 'cache'
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres-data:
  redis_data: