rootProject.name = 'viki-ecommerce-sdk'

include 'sources:bom'

include 'sources:starters:common'
include 'sources:starters:pubsub'
include 'sources:starters:datasource'
include 'sources:starters:security'
include 'sources:starters:servicediscovery'
include 'sources:starters:temporal'

include 'sources:services:eureka-server'
include 'sources:services:gateway-server'
include 'sources:services:auth-service'
include 'sources:services:catalog-service'
include 'sources:services:order-service'

