rootProject.name = 'viki-ecommerce-sdk'

include 'bom'

include 'starters:common'
include 'starters:pubsub'
include 'starters:datasource'

include 'utils:eureka-server'
include 'utils:gateway-server'

include 'services:auth-service'
include 'services:catalog-service'
include 'services:order-service'
