spring:
  sql:
    init:
      mode: always
      data-locations: classpath:mock.sql
  cloud:
    discovery:
      enabled: false


eureka:
  client:
    enabled: false
  instance:
    enabled: false
