spring:
  application:
    name: catalog
  datasource:
    url: jdbc:postgresql://${ECOMMERCE_DB_HOST}/${ECOMMERCE_DB}
    username: ${ECOMMERCE_DB_USER}
    password: ${ECOMMERCE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: flyway
    default-schema: flyway
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /catalog/