openapi: 3.0.1
info:
  title: catalog-service
  version: 1.0

paths:
  /v1/product/{productId}:
    get:
      summary: Get product and its variants using its ID
      description: Get product using its ID
      operationId: getProduct
      tags:
        - ProductController
      parameters:
        - name: productId
          in: path
          description: Product UUID
          required: true
          schema:
            type: string
            format: uuid
          examples:
            PRODUCT_EXISTS:
              value: d3b07384-d113-46e4-a710-84279a063516
            PRODUCT_NOT_EXISTS:
              value: d3b07384-d113-46e4-a710-84279a063517
      responses:
        '200':
          description: Product Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductDto"
components:
  schemas:
    ProductDto:
      type: object
      properties:
        productId:
          type: string
          format: uuid
        variants:
          type: array
          items:
            $ref: "#/components/schemas/VariantDto"
    VariantDto:
      type: object
      properties:
        variantId:
          type: string
          format: uuid
        price:
          type: number
          format: double
          example: 500