dependencies {
    implementation(project(':starters:common'))
    // Web MVC
    api 'org.springframework.boot:spring-boot-starter-webmvc'
    // Security
    api 'org.springframework.boot:spring-boot-starter-security'
    api 'io.jsonwebtoken:jjwt-api'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson'
}