eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Point to your Eureka server
  instance:
    prefer-ip-address: true # Register using IP rather than hostname (great for Docker)
