subprojects {

    apply plugin: 'java-library'
    apply plugin: 'org.springframework.boot'

    dependencies {
        implementation platform(project(':sources:bom'))
        compileOnly platform(project(':sources:bom'))
        annotationProcessor platform(project(':sources:bom'))
        testCompileOnly platform(project(':sources:bom'))
        testAnnotationProcessor platform(project(':sources:bom'))
        // Starter
        implementation 'org.springframework.boot:spring-boot-starter'
        // lombok
        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'
        testCompileOnly 'org.projectlombok:lombok'
        testAnnotationProcessor 'org.projectlombok:lombok'
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        // Tests
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    tasks.named('test') {
        useJUnitPlatform()
    }
}