spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Automatically turns Eureka service IDs into routes
          lower-case-service-id: true # Allows calling via lowercase