spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # Don't register the server itself
    fetch-registry: false       # Don't fetch registry info (it's the source)
  server:
    wait-time-in-ms-when-sync-empty: 0