dependencies {
    implementation(project(':starters:datasource'))
    implementation(project(':starters:security'))
    // Cache
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    // Kafka
    implementation 'org.springframework.boot:spring-boot-starter-kafka'
    // Integration
    implementation 'org.springframework.integration:spring-integration-core'
    implementation 'org.springframework.integration:spring-integration-kafka'
    // Eureka
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
}

