plugins {
    id 'java-platform'
}

javaPlatform {
    allowDependencies()
}

dependencies {
    // 1. Import external BOMs you want to bundle together
    api platform("org.springframework.boot:spring-boot-dependencies:4.1.1")
    api platform("org.springframework.cloud:spring-cloud-dependencies:2025.1.3")

    constraints {

        // Open API
        api 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.1.0'

        // JSON Web Token deps
        api 'io.jsonwebtoken:jjwt-api:0.12.5'
        api 'io.jsonwebtoken:jjwt-impl:0.12.5'
        api 'io.jsonwebtoken:jjwt-jackson:0.12.5'

        // Mapstruct
        api 'org.mapstruct:mapstruct:1.6.3'
        api 'org.mapstruct:mapstruct-processor:1.6.3'
        api 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    }
}