dependencies {
    // Common
    implementation(project(':starters:common'))
    // JPA
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    runtimeOnly 'org.postgresql:postgresql'
    // Flyway
    implementation 'org.springframework.boot:spring-boot-starter-flyway'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql'
    testImplementation 'org.springframework.boot:spring-boot-starter-flyway-test'
}